# ───────────────────────────────────────────────────────
# Mist Render Module
# ───────────────────────────────────────────────────────

config_version: 1

inventory:
  enable: true
  prefix:
    - "[inv]"
    - "[inventory]"
  processor: "<aqua><italic>[<papi:player_name>'s Inventory]</aqua>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s inventory"

item:
  enable: true
  prefix:
    - "[item]"
    - "[hand]"
  processor: "<yellow>[<item><reset><yellow>]</yellow>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s held item"

ender_chest:
  enable: true
  prefix:
    - "[enderchest]"
    - "[ec]"
    - "[ender]"
  processor: "<yellow><italic>[<papi:player_name>'s Ender Chest]</yellow>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s ender chest"

shulker_box:
  enable: true
  prefix:
    - "[shulker]"
    - "[shulkerbox]"
  processor: "<light_purple><italic>[<papi:player_name>'s Shulker]</light_purple>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s shulker box"