# ───────────────────────────────────────────────────────
# Mist Render Module
# ───────────────────────────────────────────────────────

config_version: 1

inventory:
  enable: true
  prefix:
    - '[inv]'
    - '[inventory]'
  processor: "<aqua><italic>[<papi:player_name>'s Inventory]</aqua>"
  hover_text:
    - "<gray>Click to view <white><papi:player_name></white>'s inventory"

item:
  enable: true
  prefix:
    - '[item]'
    - '[i]'
    - '[hand]'
  processor: "<gold>[<item><reset><gold>]</gold>"
  hover_text:
    - "<gray>Click to view <white><papi:player_name></white>'s held item"

ender_chest:
  enable: true
  prefix:
    - '[enderchest]'
    - '[ec]'
    - '[ender]'
  processor: "<yellow><italic>[<papi:player_name>'s Ender Chest]</yellow>"
  hover_text:
    - "<gray>Click to view <white><papi:player_name></white>'s ender chest"

shulker_box:
  enable: true
  prefix:
    - '[shulker]'
    - '[shulkerbox]'
  processor: "<purple><italic>[<papi:player_name>'s Shulker]</purple>"
  hover_text:
    - "<gray>Click to view <white><papi:player_name></white>'s shulker box"