[versions]
paper = "1.21.8-R0.1-SNAPSHOT"
xlibrary = "1.0.0"
caffeine = "3.2.3"
lombok = "1.18.36"
placeholder-api = "2.11.7"
luckperms = "5.4"
evo-inflector = "1.3"
cloud-paper = "2.0.0-beta.10"
cloud-annotations = "2.0.0"
folia-lib = "0.5.1"
h2 = "2.4.240"
mongodb-driver-sync = "5.6.2"
hikaricp = "7.0.2"
lettuce = "7.2.1.RELEASE"
gson = "2.13.2"
protobuf = "4.33.4"
jnats = "2.25.1"
jetbrains-annotations = "26.0.2"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
xlibrary = { module = "com.xyrisdev:XLibrary", version.ref = "xlibrary" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
placeholder-api = { module = "me.clip:placeholderapi", version.ref = "placeholder-api" }
luckperms = { module = "net.luckperms:api", version.ref = "luckperms" }
evo-inflector = { module = "org.atteo:evo-inflector", version.ref = "evo-inflector" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-paper" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud-annotations" }
folia-lib = { module = "com.tcoded:FoliaLib", version.ref = "folia-lib" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb-driver-sync" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
lettuce = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
jnats = { module = "io.nats:jnats", version.ref = "jnats" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
