# ───────────────────────────────────────────────────────
# rendering
# ───────────────────────────────────────────────────────
#
# controls interactive chat rendering features.
# allows players to preview inventories, items and commands via chat.
#
# settings:
# - enabled: toggles the feature
# - prefix: triggers used in chat messages
# - processor: rendered display text
# - hover_text: text shown on hover
#
inventory:
  enabled: true
  prefix:
    - "[inv]"
    - "[inventory]"
  processor: "<m_light_blue><italic>[<papi:player_name>'s Inventory]</italic></m_light_blue>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s inventory"

item:
  enabled: true
  prefix:
    - "[item]"
    - "[hand]"
  processor: "<m_light_green>[<item><reset><m_light_green>]</m_light_green>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s held item"

ender_chest:
  enabled: true
  prefix:
    - "[enderchest]"
    - "[ec]"
    - "[ender]"
  processor: "<m_light_yellow><italic>[<papi:player_name>'s Ender Chest]</italic></m_light_yellow>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s ender chest"

shulker_box:
  enabled: true
  prefix:
    - "[shulker]"
    - "[shulkerbox]"
  processor: "<m_light_purple><italic>[<papi:player_name>'s Shulker]</italic></m_light_purple>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s shulker box"

command:
  enabled: true
  prefix:
    - "[cmd:$cmd]"
    - "[command:$cmd]"
  processor: "<m_blue>[<full_cmd>]</m_blue>"
  hover_text:
    - "<gray>Click to execute command"

# do not edit this value
# used for automatic migration tracking
config_version: 1