# ───────────────────────────────────────────────────────
# Mist Rendering
# ───────────────────────────────────────────────────────
inventory:
  enable: true
  prefix:
    - "[inv]"
    - "[inventory]"
  processor: "<m_light_blue><italic>[<papi:player_name>'s Inventory]</italic></m_light_blue>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s inventory"

item:
  enable: true
  prefix:
    - "[item]"
    - "[hand]"
  processor: "<m_light_green>[<item><reset><m_light_green>]</m_light_green>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s held item"

ender_chest:
  enable: true
  prefix:
    - "[enderchest]"
    - "[ec]"
    - "[ender]"
  processor: "<m_light_yellow><italic>[<papi:player_name>'s Ender Chest]</italic></m_light_yellow>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s ender chest"

shulker_box:
  enable: true
  prefix:
    - "[shulker]"
    - "[shulkerbox]"
  processor: "<m_light_purple><italic>[<papi:player_name>'s Shulker]</italic></m_light_purple>"
  hover_text:
    - "<gray>Click to view <papi:player_name>'s shulker box"

# Used for migrations. DO NOT EDIT.
config_version: 1